name: "Update Runtime Data"

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/update-data.yml
permissions:
  pull-requests: write
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
      - name: Download Fastly CLI
        uses: robinraju/release-downloader@v1.9
        with:
          repository: fastly/cli
          latest: true
          fileName: fastly_*_linux_amd64.deb
      - name: Install Fastly CLI
        run: sudo dpkg -i fastly_*_linux_amd64.deb && fastly version
      - run: pnpm install
      - name: Get browser tests
        uses: actions/checkout@v4
        with:
          repository: openwebdocs/mdn-bcd-collector
          path: .bcd
      - run: npm install --ignore-scripts
        working-directory: .bcd
      - run: npm run build
        working-directory: .bcd
      - run: |
          cp .bcd/tests.json data/tests.json
          pnpm prettier data -w
          pnpm generate
      - name: Get runtime versions
        id: get-versions
        run: scripts/version.sh >> "$GITHUB_OUTPUT"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          add-paths: |
            src/runtimes/*/data.json
            packages/data/data.json
            data/tests.json
          title: "fix: update runtime compat data"
          body: |
            Updates the runtime compat data.
            Runtime versions: ${{ steps.get-versions.outputs.versions }}
          base: main
